export const searchActionsTypes = {
    RETURN_SEARCH_RESULTS: "RETURN_SEARCH_RESULTS",
    BOOK_TICKET : "BOOK_TICKET",
    REMOVE_BOOKING: "REMOVE_BOOKING",
    SAVE_BOOKINGS: "SAVE_BOOKINGS",
    FILTER_BY_NAME: "FILTER_BY_NAME",
    SORT_BY_PRICE_ASC: "SORT_BY_PRICE_ASC",
    SORT_BY_PRICE_DESC: "SORT_BY_PRICE_DESC",
    SORT_BY_TIME_ASC: "SORT_BY_TIME_ASC",
    SORT_BY_TIME_DESC: "SORT_BY_TIME_DESC",
    FIND_TOTAL: "FIND_TOTAL"
}
